/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Model_c8t6' 
 * Target:  'Model' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "apm32f10x.h"

/* Keil::Data Exchange:JSON:Jansson@2.7.0 */
#define JANSSON


#endif /* RTE_COMPONENTS_H */
